// Generated by CoffeeScript 1.3.3
(function() {

  describe(finit, function() {
    return it('works', function() {
      return expect(finit).toEqual(jasmine.any(Function));
    });
  });

}).call(this);
